#!/bin/bash
echo "=== Kosmet.io Vercel Deploy ==="
echo ""
echo "1. Create GitHub Personal Access Token:"
echo "   - Go to: https://github.com/settings/tokens"
echo "   - Click 'Generate new token'"
echo "   - Name: 'Kosmet Deploy'"
echo "   - Expiration: 30 days"
echo "   - Permissions: 'repo' (full control)"
echo "   - Generate and COPY the token"
echo ""
echo "2. Run this command with your token:"
echo "   curl -X POST https://api.github.com/user/repos \\"
echo "     -H 'Authorization: token YOUR_TOKEN_HERE' \\"
echo "     -d '{\"name\":\"kosmet-website\",\"private\":false}'"
echo ""
echo "3. Then push code:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/kosmet-website.git"
echo "   git push -u origin main"
echo ""
echo "4. Deploy on Vercel:"
echo "   - Go to: https://vercel.com/new"
echo "   - Import GitHub repo 'kosmet-website'"
echo "   - Deploy"
echo ""
echo "Or use Netlify (easier):"
echo "   - Go to: https://app.netlify.com"
echo "   - Drag 'kosmet-website' folder"
echo "   - Done."